Dataman toplevelscreens
Technoculture/VVplus pull request #43
Opened 2022-12-13 05:57 UTC by cr1spyvada

2022-12-13 13:43 UTC, sutyum commented
Add a task checklist to the description of the pr. refer to other merger prs on this repo for reference. @cr1spyvada 
Request for a review when the task is done

2022-12-14 08:40 UTC, chandantiwari1 reviewed
no issue

2022-12-27 10:06 UTC, sutyum requested changes

2022-12-27 10:06 UTC, sutyum commented on apps/Dataman/src/screens/account.tsx
> +const styles = StyleSheet.create({
Why is this needed? why can this not be done using tailwind?

2022-12-27 10:06 UTC, sutyum commented on apps/Dataman/src/screens/home.tsx
> +const styles = StyleSheet.create({
tailwind

2022-12-27 10:06 UTC, sutyum commented on apps/Dataman/src/screens/home.tsx
> +  const listMap = [
use a better/less generic name

2022-12-27 10:06 UTC, sutyum commented on apps/Dataman/src/screens/notifications.tsx
> +const styles = StyleSheet.create({
tailwind

2022-12-27 13:03 UTC, sutyum approved these changes

2022-12-27 13:03 UTC, merged