feat: created store screen
Technoculture/VVplus pull request #52
Opened 2022-12-22 06:34 UTC by cr1spyvada

2022-12-27 10:01 UTC, sutyum requested changes

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/_app.tsx
> +  React.useEffect(() => {
why do we need to load font in this manner? share reference

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/branchReceive.tsx
> +      <ScrollView>
refactor this into an array containing list data and use .map() to iteratate over this list in order to create the list view

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/branchSend.tsx
> +          <List.Item arrow="horizontal">
refactor this into an array containing list data and use .map() to iteratate over this list in order to create the list view

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/phaseToPhase.tsx
> +          </List.Item>
refactor this into an array containing list data and use .map() to iteratate over this list in order to create the list view

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/stockIssue.tsx
> +              Stock Issue Entry
refactor this into an array containing list data and use .map() to iteratate over this list in order to create the list view

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/stockRecieve.tsx
> +          </List.Item>
refactor this into an array containing list data and use .map() to iteratate over this list in order to create the list view

2022-12-27 10:01 UTC, sutyum commented on apps/Dataman/src/screens/store.tsx
> +const styles = StyleSheet.create({
why is this needed?

2022-12-28 06:53 UTC, cr1spyvada commented on apps/Dataman/src/_app.tsx
> +  React.useEffect(() => {
It's mentioned in the docs that we have to load the fonts, while setting up the ant design library in the project.
https://rn.mobile.ant.design/docs/react/introduce
![image](https://user-images.githubusercontent.com/82634732/209770301-3db011d6-3f60-4f66-bd7d-f2cc3532083c.png)

2022-12-28 11:51 UTC, sutyum approved these changes

2022-12-28 11:51 UTC, merged